#  Name: Fossenier, Logan
#  NSID: hzv143
#  Student Number: 11343891

CC = gcc
CFLAGS = -g -O0
CPPFLAGS = -std=gnu90 -Wall -Werror -Wextra -Wsign-conversion -pedantic -I.

BUILD_DIR = ./build/$(shell uname -s)-$(shell uname -m)
LIB_DIR = ./lib/$(shell uname -s)-$(shell uname -m)
BIN_DIR = ./bin/$(shell uname -s)-$(shell uname -m)

LDFLAGS = -L$(LIB_DIR)

LIB_OBJS = ########

# My make targets
.PHONY : all clean clean-full

# Make the executable
